// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// gpio6_in //
// -------- //

#define gpio6_in_wrap_target 0
#define gpio6_in_wrap 6
#define gpio6_in_pio_version 0

static const uint16_t gpio6_in_program_instructions[] = {
            //     .wrap_target
    0xa0c3, //  0: mov    isr, null
    0x4006, //  1: in     pins, 6
    0xa046, //  2: mov    y, isr
    0x00a5, //  3: jmp    x != y, 5
    0x0000, //  4: jmp    0
    0x8020, //  5: push   block
    0xa022, //  6: mov    x, y
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program gpio6_in_program = {
    .instructions = gpio6_in_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = gpio6_in_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config gpio6_in_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + gpio6_in_wrap_target, offset + gpio6_in_wrap);
    return c;
}

static inline pio_sm_config gpio6_in_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + gpio6_in_wrap_target, offset + gpio6_in_wrap);
    return c;
}

#endif

